version: '2'

services:
  app:
    extends:
      file: ./docker/compose/supply.yml
      service: dependencies
    environment:
      NODE_ENV: development
    ports:
      - 3005:2999 # - host's port:container's port
    command: yarn run start
