version: '2'

services:
  deps:
    image: js/node
    command: yarn install
    volumes:
      - ~/yarn_cache/:/tmp/cache/yarn/
      - ../../source/:/home/jan/app/ # replace 'your_host_user' for the name of your host user
