version: '2'

services:
  dependencies:
    image: js/node
    command: yarn install
    volumes:
      - ~/yarn_cache/:/tmp/cache/yarn/
      - ../../source/app/:/home/jan/app/ # replace '__YOUR_HOST_USER__' for the name of your host user
